# -*- coding: utf-8 -*-
"""exercicio_1_AyrtonCossuol.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11E7Zd8Y4Bk3ja7uwyAgHvBE2iStFHyeV
"""

#Atividade 1
import numpy as np
import matplotlib.pyplot as plt

def funcao_r_normal():
  t = np.arange(0,0.2,0.001)
  r = -1 * (1 + 0.5 * np.cos(20 * np.pi * t))

  return r

def funcao_r_adiantada():
  t = np.arange(0.05,0.2,0.001)
  r = -1 * (1 + 0.5 * np.cos(20 * np.pi * t))

  return r

def main():
  t = np.arange(0,0.2,0.001)
  t_1 = np.arange(0.05,0.2,0.001)

  r = funcao_r_normal()
  r_2 = funcao_r_adiantada()

  plt.figure(figsize=(12, 6))
  plt.plot(t,r)
  plt.xlabel("(t)")
  plt.ylabel("r(t)")
  plt.title('Resposta do circuito para quando t0 = 0 segundos')
  plt.show()

  plt.figure(figsize=(12, 6))
  plt.plot(t_1,r_2)
  plt.xlabel("(t)")
  plt.ylabel("r_2(t)")
  plt.title('Resposta do circuito para quando t0 = 50 milisegundos')
  plt.show()

if __name__== "__main__":
  main()
  print("Com analise dos graficos, pode ser percebido que o sistema é invariante no tempo.")