# -*- coding: utf-8 -*-
"""exercicio_3_AyrtonCossuol.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BRaYDthRlrFi_O-PrVump_FoVbS0lIUO
"""

#Atividade 3
import numpy as np
import matplotlib.pyplot as plt

def v_inicial(const):
  v = []
  for i in np.arange(0, 4, 0.001):
    v.append(const * np.cos(np.pi * i))

  return v

def v_out(v1):
  v_saida = []

  for i in np.arange(0, 4000):
    if v1[i] > 0.5:
      v_saida.append(0.5)
    elif v1[i] < -0.5:
      v_saida.append(-0.5)
    else:
      v_saida.append(v1[i])

  return v_saida

def main():
  t_0 = np.arange(0, 4, 0.001)

  v1 = v_inicial(1)
  v2 = v_inicial(0.3)

  v_saida = v_out(v1)
  v_saida_2 = v_out(v2)

  plt.figure(figsize=(12, 6))
  plt.plot(t_0, v1)
  plt.xlabel("(t)")
  plt.ylabel("Vi(t)")
  plt.title('Sinal Vi(t)')
  plt.show()

  plt.figure(figsize=(12, 6))
  plt.plot(t_0, v_saida)
  plt.xlabel("(t)")
  plt.ylabel("Vout(t)")
  plt.title('Sinal Vout(t)')
  plt.show()

  plt.figure(figsize=(12, 6))
  plt.plot(t_0, v2)
  plt.xlabel("(t)")
  plt.ylabel("Vi(t)")
  plt.title('Sinal Vi(t) multiplicado por 0.3')
  plt.show()

  plt.figure(figsize=(12, 6))
  plt.plot(t_0, v_saida_2)
  plt.xlabel("(t)")
  plt.ylabel("Vout(t)")
  plt.title('Sinal Vout(t) com o sinal Vi multiplicado por 0.3')
  plt.show()

if __name__ == "__main__":
  main()
  print('A - O diodo não é Linear.')
  print('B - O sistema é invariante no tempo.')

