# -*- coding: utf-8 -*-
"""exercicio_4_F_AyrtonCossuol.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11E7Zd8Y4Bk3ja7uwyAgHvBE2iStFHyeV
"""

#Atividade 4 - F
import numpy as np
import matplotlib.pyplot as plt

def degrau(n0, sinal):
  u = []

  for i in range(-2, 21):
    if i >= n0:
      u.append((np.sin((1/12)* np.pi * i)) * 1) if sinal == 1 else u.append((np.sin((1/12)* np.pi * i)) * -1)

    else:
      u.append((np.sin((1/12)* np.pi * i)) * 0)

  return u

def degrau_normal():
  u = []

  for i in range(-2, 21):
    u.append(1) if i >= 0 else u.append(0)

  return u

def main():
  n = np.linspace(-2, 20, 23)
  n_2 = np.linspace(-4, 40, 45)

  h = degrau(3, 1)
  x = degrau_normal()

  y = np.convolve(x, h)

  plt.figure(figsize=(12, 6))
  plt.stem(n, h, use_line_collection = True)
  plt.xlabel("[n]")
  plt.ylabel("h[n]")
  plt.title('Sinal h[n]')
  plt.show()

  plt.figure(figsize=(12, 6))
  plt.stem(n, x, use_line_collection = True)
  plt.xlabel("[n]")
  plt.ylabel("x[n]")
  plt.title('Sinal x[n]')
  plt.show()

  plt.figure(figsize=(12, 6))
  plt.stem(n_2, y, use_line_collection = True)
  plt.xlabel("[n]")
  plt.ylabel("y[n]")
  plt.title('Sinal y[n]')
  plt.show()

if __name__ == "__main__":
  main()