# -*- coding: utf-8 -*-
"""exercicio_5_C_AyrtonCossuol.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BRaYDthRlrFi_O-PrVump_FoVbS0lIUO
"""

#Atividade 5 - C
import numpy as np
import matplotlib.pyplot as plt

def trem_impulso():
  imp = []

  for i in range(len(np.linspace(-3, 3, 13))):
    imp.append(1) if i % 3 == 0 else imp.append(0)

  return imp

def pulso_triangulo():
  t = []

  for i in range(len(np.linspace(-3, 3, 13))):
    if i <= 4:
      t.append(0)
    elif i == 5 or i == 7:
      t.append(0.5)
    elif i == 6:
      t.append(1)
    else:
      t.append(0)

  return t

def main():
  n = np.linspace(-3, 3, 13)
  n_2 = np.linspace(-6, 6, 25)

  x = trem_impulso()
  h = pulso_triangulo()

  y = np.convolve(x, h) 

  plt.figure(figsize=(12, 6))
  plt.stem(n, x, use_line_collection = True)
  plt.xlabel("[n]")
  plt.ylabel("x[n]")
  plt.title('Sinal x[n] para T = 3/2')
  plt.show()

  plt.figure(figsize=(12, 6))
  plt.plot(n, h)
  plt.xlabel("[n]")
  plt.ylabel("h[n]")
  plt.title('Sinal h[n]')
  plt.show()

  plt.figure(figsize=(12, 6))
  plt.plot(n_2, y)
  plt.xlabel("[n]")
  plt.ylabel("y[n]")
  plt.title('Sinal y[n]')
  plt.show()

if __name__ == "__main__":
  main()

