# -*- coding: utf-8 -*-
"""exercicio_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LfK1jYQbDAEhcMaHgEHyQxrPlzZSSlvw
"""

import numpy as np
import matplotlib.pyplot as plt

if __name__ == "__main__":
  t = np.linspace(0, 5, 1000)

  expoente_1 = -2 * t
  x_1 = 10 * np.exp(expoente_1) * np.sin(30 * np.pi * t + (np.pi/2))

  plt.figure(figsize=(12, 6))
  plt.axis([-0.05, 3, -10.02, 11.02])
  plt.plot(t, x_1)
  plt.title('Função da alternativa A')
  plt.xlabel('t')
  plt.ylabel('x(t)')

  plt.show()
  ###########################

  expoente_2 = -2 * t
  x_2 = 10 * np.exp(expoente_2) * np.sin(30 * np.pi * t)

  plt.figure(figsize=(12, 6))
  plt.axis([-0.05, 3, -10.02, 10.02])
  plt.plot(t, x_2)
  plt.title('Função da alternativa B')
  plt.xlabel('t')
  plt.ylabel('x(t)')

  plt.show()
  ###########################

  expoente_3 = 2 * t
  x_3 = 10 * np.exp(expoente_3) * np.sin(30 * np.pi * t)

  plt.figure(figsize=(12, 6))
  plt.plot(t, x_3)
  plt.title('Função da alternativa C')
  plt.xlabel('t')
  plt.ylabel('x(t)')

  plt.show()

