# -*- coding: utf-8 -*-
"""exercicio_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LfK1jYQbDAEhcMaHgEHyQxrPlzZSSlvw
"""

import numpy as np
import matplotlib.pyplot as plt

if __name__ == "__main__":
  t = np.arange(0, 2 * np.pi, 0.001)

  x = 2 * np.cos(30 * np.pi * t)

  plt.figure(figsize=(16, 8))
  plt.axis([0, 1, -2.15, 2.15])
  plt.plot(3*t, x)
  plt.scatter(0.2, 2, color='black')
  plt.scatter(0.3, -2, color='red')
  plt.legend(['Função cosseno', 'Ponto de maximo', 'Ponto de minimo'])
  plt.xlabel('t')
  plt.ylabel('x(t)')

  plt.show()

