# -*- coding: utf-8 -*-
"""exercicio_3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LfK1jYQbDAEhcMaHgEHyQxrPlzZSSlvw
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy import signal

def square(wt, duty):
  pwm = signal.square(wt, duty)

  plt.figure(figsize=(12, 6))
  plt.plot(t, pwm)
  plt.title('Função proposta')
  plt.xlabel('t')
  plt.ylabel('x(t)')

  plt.show()


if __name__ == "__main__":
  t = np.linspace(0, 5, 500, endpoint=False)

  wt = 10 * np.pi * t
  
  square(wt, 0.2)

