# -*- coding: utf-8 -*-
"""exercicio_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LfK1jYQbDAEhcMaHgEHyQxrPlzZSSlvw
"""

import numpy as np
import matplotlib.pyplot as plt

def triangular(w0t):

  plt.figure(figsize=(12, 6))
  plt.axis([-0.01, 1, -2.01, 2.01])
  plt.plot(t, signal.sawtooth(w0t, width=0.5))
  plt.show()

if __name__ == "__main__":
  t = np.linspace(0, 5, 500, endpoint=False)
  w0t = 10 * np.pi * t

  triangular(w0t)

