# -*- coding: utf-8 -*-
"""exercicio_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LfK1jYQbDAEhcMaHgEHyQxrPlzZSSlvw
"""

import numpy as np
import matplotlib.pyplot as plt

if __name__ == "__main__":
  t = np.arange(0, 2 * np.pi, 0.001)

  x_1 = 2 * np.cos(30 * np.pi * t)
  x_2 = x_1 + (5/2) * np.cos(60 * np.pi * t)

  plt.figure(figsize=(16, 8))
  plt.axis([-0.02, 1, -3, 6])
  plt.plot(3*t, x_2)
  plt.legend(['Função cosseno somada'])
  plt.xlabel('t')
  plt.ylabel('x(t)')

  plt.show()

