# -*- coding: utf-8 -*-
"""exercicio_1_D_AyrtonCossuol.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FwOyhO10ytpCkbBIfeGf4WkqtnmUwM0I
"""

# Atividade 1 - d  -  Ayrton Cossuol
import numpy as np
import matplotlib.pyplot as plt
from numpy.fft import fft, ifft, fftfreq, fftshift

def cria_sinal(n):
  x = []

  for i in n:
    x.append(np.power(0.9 * np.exp(1j * (np.pi / 3)), i)) if i >= 0 else x.append(0)

  return x
def main():
  L = 256
  n = np.arange(0, L)

  x = cria_sinal(n)

  X = fft(x)

  w = fftfreq(len(X), d=1.0) * (2 * np.pi)
  
  wd = fftshift(w / np.pi)
  X_d = fftshift(X)

  Mod_X = np.abs(X_d)
  phas_X = np.angle(X_d)


  fig1, ax = plt.subplots(3, 1)
  ax[0].stem(n, x, 'r-', use_line_collection = True)
  ax[0].set_ylabel("Amplitude")
  ax[0].set_xlabel("amostras")
  ax[0].set_xlim(-2, 40)
  ax[0].set_title('x[n]')
  ax[0].grid(True)

  ax[1].plot(wd, Mod_X, 'r-', linewidth=2)
  ax[1].set_ylabel("Amplitude")
  ax[1].set_xlabel("w/pi")
  ax[1].set_title('|X[k]|')
  ax[1].grid(True)

  ax[2].plot(wd, phas_X, 'r-', linewidth=2)
  ax[2].set_ylabel("Amplitude")
  ax[2].set_xlabel("w/pi")
  ax[2].set_title('angle(X[k])')
  ax[2].grid(True)

  fig1.tight_layout()
  plt.show()

if __name__ == "__main__":
  main()

