# -*- coding: utf-8 -*-
"""separaParImpar.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jufhLacc0hYWmaGo6Y-Kimio0OnRvCly
"""

def separaParImpar(s):
  sinal_par = []
  sinal_impar = []

  for j in range(len(s)):
    sinal_par.append(1/2 * (s[j] + s[len(s)-j-1]))
    sinal_impar.append(1/2 * (s[j] - s[len(s)-j-1]))

  return sinal_par, sinal_impar

s = [2, 1, 0, 1, 2]
#s = [-2, -1, 0, 1, 2]
#s = [0, 0, 0, 2, 4]
#s = [0, -1, -1, 3, 2]

p, i = separaParImpar(s)
print('Função Par      ->', p)
print('Função Impar    ->', i)
print('Função Original ->', s)

